import './globals.css';
import { Inter } from 'next/font/google';
import { getServerSession } from 'next-auth';
import Provider from './components/Provider';
import Navbar from './components/Navbar';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOptions);
	console.log('layout session', session);

	return (
		<html lang='en'>
			<body className={inter.className}>
				<Provider session={session}>
					<Navbar />
					{children}
				</Provider>
			</body>
		</html>
	);
}
